titlt: INSA MANE
LOGO: img/nny.jpg
des cription: porfolio Étudiant en Licence 2 en Infographie et Design Numérique, passionné par la narration visuelle et les métiers de l'image
show_download: true
theme: jekyll-theme-minimal
lang: fr
